# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: btMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Color_pb2 as Color__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='btMessage.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0f\x62tMessage.proto\x1a\x0b\x43olor.proto\"f\n\tBTMessage\x12\x1d\n\x04type\x18\x01 \x01(\x0e\x32\x0f.BTMessage.Type\x12\x15\n\x05\x63olor\x18\x02 \x01(\x0b\x32\x06.Color\"#\n\x04Type\x12\t\n\x05\x43OLOR\x10\x00\x12\x07\n\x03\x42\x41R\x10\x01\x12\x07\n\x03\x42\x41Z\x10\x02\x62\x06proto3')
  ,
  dependencies=[Color__pb2.DESCRIPTOR,])



_BTMESSAGE_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='BTMessage.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='COLOR', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BAR', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BAZ', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=99,
  serialized_end=134,
)
_sym_db.RegisterEnumDescriptor(_BTMESSAGE_TYPE)


_BTMESSAGE = _descriptor.Descriptor(
  name='BTMessage',
  full_name='BTMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='BTMessage.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='color', full_name='BTMessage.color', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _BTMESSAGE_TYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=134,
)

_BTMESSAGE.fields_by_name['type'].enum_type = _BTMESSAGE_TYPE
_BTMESSAGE.fields_by_name['color'].message_type = Color__pb2._COLOR
_BTMESSAGE_TYPE.containing_type = _BTMESSAGE
DESCRIPTOR.message_types_by_name['BTMessage'] = _BTMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BTMessage = _reflection.GeneratedProtocolMessageType('BTMessage', (_message.Message,), dict(
  DESCRIPTOR = _BTMESSAGE,
  __module__ = 'btMessage_pb2'
  # @@protoc_insertion_point(class_scope:BTMessage)
  ))
_sym_db.RegisterMessage(BTMessage)


# @@protoc_insertion_point(module_scope)
