# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CustomAnim.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Stripe_pb2 as Stripe__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='CustomAnim.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x10\x43ustomAnim.proto\x1a\x0cStripe.proto\"2\n\nCustomAnim\x12\x17\n\x06\x66rames\x18\x01 \x03(\x0b\x32\x07.Stripe\x12\x0b\n\x03\x66ps\x18\x02 \x01(\x05\x62\x06proto3')
  ,
  dependencies=[Stripe__pb2.DESCRIPTOR,])




_CUSTOMANIM = _descriptor.Descriptor(
  name='CustomAnim',
  full_name='CustomAnim',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frames', full_name='CustomAnim.frames', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fps', full_name='CustomAnim.fps', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=84,
)

_CUSTOMANIM.fields_by_name['frames'].message_type = Stripe__pb2._STRIPE
DESCRIPTOR.message_types_by_name['CustomAnim'] = _CUSTOMANIM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CustomAnim = _reflection.GeneratedProtocolMessageType('CustomAnim', (_message.Message,), dict(
  DESCRIPTOR = _CUSTOMANIM,
  __module__ = 'CustomAnim_pb2'
  # @@protoc_insertion_point(class_scope:CustomAnim)
  ))
_sym_db.RegisterMessage(CustomAnim)


# @@protoc_insertion_point(module_scope)
