# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Led.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Led.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\tLed.proto\">\n\x03Led\x12\r\n\x05index\x18\x01 \x01(\x05\x12\x0b\n\x03red\x18\x02 \x01(\x05\x12\r\n\x05green\x18\x03 \x01(\x05\x12\x0c\n\x04\x62lue\x18\x04 \x01(\x05\x62\x06proto3')
)




_LED = _descriptor.Descriptor(
  name='Led',
  full_name='Led',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='Led.index', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='red', full_name='Led.red', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='green', full_name='Led.green', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='blue', full_name='Led.blue', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=75,
)

DESCRIPTOR.message_types_by_name['Led'] = _LED
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Led = _reflection.GeneratedProtocolMessageType('Led', (_message.Message,), dict(
  DESCRIPTOR = _LED,
  __module__ = 'Led_pb2'
  # @@protoc_insertion_point(class_scope:Led)
  ))
_sym_db.RegisterMessage(Led)


# @@protoc_insertion_point(module_scope)
