# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Stripe.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Led_pb2 as Led__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Stripe.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0cStripe.proto\x1a\tLed.proto\"\x1c\n\x06Stripe\x12\x12\n\x04leds\x18\x01 \x03(\x0b\x32\x04.Ledb\x06proto3')
  ,
  dependencies=[Led__pb2.DESCRIPTOR,])




_STRIPE = _descriptor.Descriptor(
  name='Stripe',
  full_name='Stripe',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='leds', full_name='Stripe.leds', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=55,
)

_STRIPE.fields_by_name['leds'].message_type = Led__pb2._LED
DESCRIPTOR.message_types_by_name['Stripe'] = _STRIPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Stripe = _reflection.GeneratedProtocolMessageType('Stripe', (_message.Message,), dict(
  DESCRIPTOR = _STRIPE,
  __module__ = 'Stripe_pb2'
  # @@protoc_insertion_point(class_scope:Stripe)
  ))
_sym_db.RegisterMessage(Stripe)


# @@protoc_insertion_point(module_scope)
